# Imagine
# @name imagine

post https://api.midjourneyapi.io/v2/imagine
Authorization: 6cb3388a-d4cb-4ebe-8f60-70d55209670b
Content-type: application/json

{
    "prompt": "https://vjeko.blob.core.windows.net/public/97B0BCA49F06FD8DDA56841DEE5DECFE112818BE.jpg in a cafe, photo, realistic --ar 1:1 --iw 2"
}

### 

@taskId = {{imagine.response.body.$.taskId}}

###

post https://api.midjourneyapi.io/v2/result
Authorization: 6cb3388a-d4cb-4ebe-8f60-70d55209670b
Content-type: application/json

{
    "taskId": 6800418486927268
}

